### ISSUE TITLE
Can we orginize sub-modules into one project?

### ISSUE THREAD

**Issue by linwukang** [cloudera/yunikorn-core#17]
There're too many sub-project for yunikorn, such as core/interface/k8s/yarn etc. I think orginize them into a single project, as sperate modules, is much better.

**Comment by yangwwei** [comment]
Hi @linwukang 

Currently, `go module` is not working nicely with multiple modules, that's my major concern. Please see doc: https://github.com/golang/go/wiki/Modules#should-i-have-multiple-modules-in-a-single-repository. Moving on, if mod can support this nicely, I am OK to put them into one single repo.

**Comment by yangwwei** [comment]
Hi @linwukang 

Hopefully, my answer makes sense to you. Anyway, I am closing this now. We have a mailing list:  yunikorn@googlegroups.com, feel free to post your messages. Also, we have our slack channel setup, see more in https://github.com/cloudera/yunikorn-core. You have a ton of choices to chat with us now : ). Thx

**Comment by linwukang** [comment]
Hi @yangwwei 
Thank you for reply, I think I have got the point, :-). But, anyway, splitting modules into different project make Yunikorn a bit hard to startup, especially, modules like core/interface are logical associated, it may introduce some compatibility issues sometime in the future, and also, it make distribution more complex.

**Comment by yangwwei** [comment]
hi @linwukang 

Initially, these modules are decoupled, there are several benefits which we think is more important.

1. Release each module separately. An example is when the core gets stable, it may have a slower release cycle comparing to k8s-shim, because k8s-shim may need to be updated when there is a K8s version update; it might also be possible core releases faster, e.g we kept pushing new stuff to it but a shim may stay relatively unchanged along that time. 
2. Support multiple shims. Keep in mind that YuniKorn is a universal scheduler, it can integrate with other systems with different shims. For example, when we have a shim for YARN, YARN users only need to download core/interface/YARN-shim without touching K8shim at all.
3. Decouple is difficult, if it is not done in the first place, it will be 10x difficult later.

What we really need is to have `go mod` support multiple modules in one repo nicely, manage different versions of them in one same repo might be the best solution. We'll keep an eye on `go mod` community and make that change when time is ready.

Thanks

**Comment by linwukang** [comment]
@yangwwei  Thanks. Really nice relay to explain the under-layer considerations. Maybe we can introduce plugin repo (shim-hub, etc) to manage shims properly in the next early iterations.

**Comment by sunilgovind** [comment]
Yes @yangwwei , i agree to this.
Having a modular design at this point helps to decouple the components very easily contributors focussing on each components can pace up the developments cycles faster.
With "go mod" improvement coming in, we will be able to handle these small issues what we face now much effective way in future
