### ISSUE TITLE
Support Best-Efforts requests

### ISSUE THREAD

**Issue by yangwwei** [cloudera/yunikorn-core#54]
There are 3 forms of QoS classes for K8s pods,
- Guaranteed
- Burstable
- Best-Effort

The 3rd one means no resource request or limit was given in the pod spec, see more here:
https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-besteffort. Right now, YuniKorn can not schedule such pod.

**Comment by wilfred-s** [comment]
Looking at the code of K8 a best effort pod has only containers without resource requests (i.e. all will be null). On the K8 side a PodQOSClass of "BestEffort" affect some processes:
- just sees "pods" as a resource to check. 
- are ignored in the node memory pressure predicate (ignoring it)
- for cgroups on linux gets a default standard slice of cpu.
- are checked first as a candidate for pre-emption

For K8 scheduling triggers on just the container number, not the resource request.

However in YuniKorn we currently use scheduling based on the `pendingResource` of a queue to schedule.  Since a best effort app does not ask for resources it will never trigger a schedule cycle.
This goes to the hart of the scheduling steps in YuniKorn. I see two ways forward:
1. we create a fake request with some default resources that are not nil
1. we properly introduce the best effort container

A fake resource request is a simple solution but leaves gaps: node usage will become out of sync with K8, does not fit well with pre-emption as the container now is a normal just small container. It also clashes with sorting policies for apps and requests etc.
Introducing a best effort container would work around the issues above but is more complex change. A resource request would need to be changed as would the scheduling steps. app and request sorting as well as preemption sort containers using  pluggable algorithms which  we can make aware of this container type.

I prefer the second option.

**Comment by yangwwei** [comment]
Thanks for the analysis @wilfred-s , cc @wangdatan , @sunilgovind .
How about we work on a quick solution with option 1? I think we can achieve it without big changes. I am not saying this is a better approach or our "final" approach. But just want to get this work with minimal effort and see how things go on. We can always get back and work out a better design like opt 2.
Just my thought here.

**Comment by wilfred-s** [comment]
That can be achieved without any core scheduler changes. 

The k8shim can handle the solution for option 1: when it finds a pod that is marked with the PodQOSClass of "BestEffort" it modifies the resource request to not be nil but have a tiny value. Doing that we do not burden the core with something that is currently shim limited.

**Comment by yangwwei** [comment]
Yeah, sounds good enough for now. Can we implement this and see how it works? Thanks!

**Comment by yangwwei** [comment]
This is done in https://github.com/cloudera/yunikorn-k8shim/pull/52. Thanks @wilfred-s !
